# Generated by Django 6.0 on 2026-07-19 07:57

from django.db import migrations, models


def blank_email_to_null(apps, schema_editor):
    """기존 회원의 빈 email("")을 NULL로 백필해 unique 제약 충돌을 방지한다."""
    Member = apps.get_model("accounts", "Member")
    Member.objects.filter(email="").update(email=None)


def null_email_to_blank(apps, schema_editor):
    Member = apps.get_model("accounts", "Member")
    Member.objects.filter(email__isnull=True).update(email="")


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        # 1단계: unique 없이 null 허용으로 변경
        migrations.AlterField(
            model_name="member",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="이메일"
            ),
        ),
        # 2단계: 빈 문자열 email을 NULL로 백필
        migrations.RunPython(blank_email_to_null, null_email_to_blank),
        # 3단계: unique 제약 적용
        migrations.AlterField(
            model_name="member",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, unique=True, verbose_name="이메일"
            ),
        ),
    ]
