# Generated by Django 6.0.7 on 2026-08-17 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_member_email'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='withdrawn_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='탈퇴일시'),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='이메일'),
        ),
        migrations.AddConstraint(
            model_name='member',
            constraint=models.UniqueConstraint(condition=models.Q(('withdrawn_at__isnull', True)), fields=('email',), name='unique_active_member_email'),
        ),
    ]
