# Generated by Django 6.0.7 on 2026-09-23 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_member_nickname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('service', '서비스 이용약관'), ('privacy', '개인정보 수집·이용 동의'), ('marketing', '마케팅 정보 수신 동의')], max_length=20, verbose_name='종류')),
                ('version', models.CharField(max_length=20, verbose_name='버전')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('is_required', models.BooleanField(default=True, verbose_name='필수 동의 여부')),
                ('effective_at', models.DateTimeField(verbose_name='시행일시')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
            ],
            options={
                'verbose_name': '약관',
                'verbose_name_plural': '약관',
                'ordering': ['kind', '-effective_at'],
                'constraints': [models.UniqueConstraint(fields=('kind', 'version'), name='unique_terms_kind_version')],
            },
        ),
    ]
