# Generated by Django 6.0.7 on 2026-09-23 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_terms'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsedRefreshToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jti', models.CharField(max_length=32, unique=True, verbose_name='토큰 ID')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='토큰 만료일시')),
                ('used_at', models.DateTimeField(auto_now_add=True, verbose_name='사용일시')),
            ],
            options={
                'verbose_name': '사용한 refresh 토큰',
                'verbose_name_plural': '사용한 refresh 토큰',
            },
        ),
    ]
