# Generated by Django 6.0 on 2026-06-03 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_category_todo_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='due_date',
            field=models.DateField(blank=True, help_text='할 일의 기한일 (선택 사항)', null=True),
        ),
    ]
